export const data = [
  {
    id: 12,
    months: "December",
    day: new Date().toLocaleString(),
    consulted: true,
    bg: "#33628F",
  },
  {
    id: 1,
    months: "January ",
    day: new Date().toLocaleString(),
    consulted: true,
    bg: "#4A82A9",
  },
  {
    id: 2,
    months: "February",
    day: new Date().toLocaleString(),
    consulted: false,
    bg: "#8CB2D9",
  },
  {
    id: 3,
    months: "March",
    day: new Date().toLocaleString(),
    consulted: true,
    bg: "#488C03",
  },
  {
    id: 4,
    months: "April",
    day: new Date().toLocaleString(),
    consulted: true,
    bg: "#A6BF49",
  },
  {
    id: 5,
    months: "May",
    day: new Date().toLocaleString(),
    consulted: true,
    bg: "#EFF294",
  },
  {
    id: 6,
    months: "June",
    day: new Date().toLocaleString(),
    consulted: true,
    bg: "#DA0136",
  },
  {
    id: 7,
    months: "July",
    day: new Date().toLocaleString(),
    consulted: true,
    bg: "#EC1050",
  },
  {
    id: 8,
    months: "August",
    day: new Date().toLocaleString(),
    consulted: true,
    bg: "#FF3A72",
  },
  {
    id: 9,
    months: "September",
    day: new Date().toLocaleString(),
    consulted: true,
    bg: "#732002",
  },
  {
    id: 10,
    months: "October",
    day: new Date().toLocaleString(),
    consulted: true,
    bg: "#A63F03",
  },
  {
    id: 11,
    months: "November",
    day: new Date().toLocaleString(),
    consulted: true,
    bg: "#BF6B04",
  },
];

export const taskData = [
  {
    id: 1,
    months: "November",
    day: new Date().toLocaleString(),
    task: "read a book",
  },
  {
    id: 2,
    months: "October",
    day: new Date().toLocaleString(),
    task: "shopping",
  },
];
